apiVersion: v1
kind: ConfigMap
metadata: { name: backend-config }
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  USER_SERVICE_BASE_URL: http://user-service:8083
  AUTH_SERVICE_BASE_URL: http://auth-service:8084
  INVENTORY_SERVICE_BASE_URL: http://inventory-service:8082
  BILLING_SERVICE_BASE_URL: http://billing-service:8085
  SALES_SERVICE_BASE_URL: http://sales-service:8081
  # DB_HOST is env-specific → set in overlay patch
